catenax-ng/catenax-ng.github.io

- docs/internal/how-to-onboard-teams-in-hotel-budapest.md
removed typos and some other things in internal guide
> removed typos

- docs/security/veracode.md
Updated repository secrets to org secrets.
> Updated veracode guides

- docs/security/veracode-jira-plugin.md
I've changed the **import schedule to hourly** and added our **distribution list** for teams to contact us.
> changed import schedule and distribution list as mail

- docs/resources.md
"Request access to an existing environment/namespace" was unnecessary/misleading and so I removed it
> removed unnecessary template in things to request

- docs/security/GitguardianShield.md
This documentation is explaining how to use the ggshield app.
> ggshield documentation added

- docs/security/GitguardianShield.md
fixing typos and minor formatting changes, no changes to the content
> improve quality of doc

- docs/guides/how-to-cross-repo-workflow-dispatch.md
> describe workflow for developers

- docs/github-checks.mdx
add object of GitHub checks into the page
> add github checks

- blog/2022-09-16-OfficeHours.md
added notes for recent office hour.
> docs: added office hour from 16.09.2022

- docs/guides/catenax-at-home.mdx
> docs: fix typo

- src/components/HomepageFeatures/index.js
> fix: 1h office hour

- docs/trg/trg-5/trg-5-1.md
Publish and set active TRG 5.01 - Helm Chart Requirements
> A1ODT-917: first release of Helm Chart Requirements

- docs/trg/trg-5/trg-5-1.md
- docs/trg/trg-5/trg-5-2.md
- docs/trg/trg-5/trg-5-3.md
fixed some typos in
trg-5-1.md
trg-5-2.md
trg-5-3.md
> fixed typos in TRG-5.x

- docs/guides/Helm/how-to-lint-and-test-your-helm-chart.md
- docs/guides/Helm/how-to-release-a-helm-chart.md
- docs/trg/trg-5/trg-5-1.md
- docs/trg/trg-5/trg-5-3.md
- package-lock.json
Aligning the TRG helm docs with requirements, best practices. Still working on the structure so just a draft is opened. Open for ideas/discussions.
> docs: align trg helm section with requirements

- blog/2022-11-04-OfficeHours.md
Add office hour to our GH page.
> Add office hour from 20221104

- docs/guides/Helm/how-to-release-a-helm-chart.md
Extended workflow to add Helm chart release to Helm chart repo
> docs: add helm chart release to helm repository

- docs/trg/trg-4/trg-4-1.md
- docs/trg/trg-4/trg-4-4.md
Initial release of TRG 4.01 - Image Tagging
> Add TRG 4.01 - Image Tagging

- blog/2022-11-18-OfficeHours.md
Added the blog post for the 2022-11-18 Office Hour. Recording need to be cut, will push edited video in new commit.
> chore: add 2022-11-18 office hour blog page

- docs/guides/kubernetes/how-to-use-persistent-storage.md
Removed broken links and reworked the page to just have essential information on how to create persistent volume claims in our clusters
> rework persistent storage documentation

- blog/2022-12-09-OfficeHours.md
add meeting minutes for recent office hour.
> docs: add office hour 2022-12-09

- docs/trg/trg-4/trg-4-1.md
- docs/trg/trg-4/trg-4-2.md
ticket: https://jira.catena-x.net/browse/A1ODT-1108
in addition, fixed a typo
> doc: mark the TG 4.02 moved

- docs/trg/trg-5/trg-5-6.md
https://jira.catena-x.net/browse/A1ODT-1116
> mark the TG moved

- docs/trg/trg-4/trg-4-2.md
- docs/trg/trg-4/trg-4-3.md
- docs/trg/trg-4/trg-4-4.md
- mark trg4.04 moved
- correct small thing in other trg
> mark the TRG4.04 moved

- docs/trg/trg-5/trg-5-6.md
- docs/trg/trg-5/trg-5-7.md
- docs/trg/trg-5/trg-5-8.md
- Add TRG 5.08 moved to eclipse
- Add missing TRG 5.07
- Fix minor typos in TRG 5.06
> Chore/update trg 5.08 move to etx

- docs/trg/trg-2/trg-2-4.md
> chore: add trg 2.04 leading product repository

- blog/2023-01-13-OfficeHours.md
Add recent System-Team office hour.
> docs: add office hour 2023-01-13

- docs/guides/Helm/how-to-lint-and-test-your-helm-chart.md
Use latest helm version 3.10.3 for testing.
> fix: update code for helm test and lint wf

- package-lock.json
- package.json
https://github.com/facebook/docusaurus/releases/tag/v2.3.0
- update docusaurus version 2.3.0 
- update easyops-cn/docusaurus-search-local 0.33.6
- update clsx 1.2.1
- update prism-react-renderer 1.3.5
> chore: update docusaurus version and dependencies

- blog/2023-02-03-OfficeHours.md
> doc: add officehour 20230203

- docs/internal/how-to-setup-forked-repo.md
- update link 
- update default repo setting archive - false
- update import terraform state
> update doc links for fork repository

- blog/2023-03-28-OfficeHours.md
Addition:
- add new Markdown File into blog section for the HO last week
- checked via markdownlint to correct markdown format
Test: 
- run 'npm start' to test if gh-page will build up with docusaurus
- should look like this:
> Add new blog post from last Office Hour on 28.03.2023

- blog/2023-04-21-OfficeHours.md
- add new blog post for last office hour
- npm test will look like this
> chore: add new blog post for office hour 24042023

- blog/2023-05-26-OfficeHours.md
> docs: add office hour 26052023

- blog/2023-06-23-OfficeHours.md
Add recent office hour to our website.
> docs: add office hour 23062023

- docs/faq.md
- package-lock.json
- package.json
- update docusaurus to version 2.4.1
- update support request link
- new version available / maintainance
- checkout this branch `chore/update-docusaurus`
- npm install
- npm start
[FaGru3n](https://github.com/FaGru3n), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>
> chore: update docusaurus

- blog/2023-07-28-OfficeHours.md
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/203
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93
> chore: add office hour blog post 28-07

- blog/2023-08-04-OfficeHours.md
Office Hour Blog post for 04. August
Session recording not yet present. Will follow later
> chore: add office hour post for 2023-08-04

- blog/2023-08-25-OfficeHours.md
> docs: add office hour meeting minutes 2023-08-25

- blog/2023-09-01-OfficeHours.md
- add blog post 
- referenced the uploaded recording
Test:
- checkout pr-branch
- npm install (optional)
- npm start 
- verify the changes
> chore: add blog post from 1.September

- blog/2023-08-18-OfficeHours.md
- add blog post from last friday
- recording was broken so added transkription file
Testing:
- checkout pr branch
- npm install (optional)
- npm start 
- verfiy changes
> chore: add missing blog post

- blog/2023-09-29-OfficeHours.md
fixes https://github.com/eclipse-tractusx/sig-infra/issues/289
> chore: add office hour file for 290923

- blog/2023-10-20-OfficeHours.md
Add meeting minutes for last office hour.
> docs: office hour 20102023

- blog/2023-11-03-OfficeHours.md
PR to add 03/11/2023 Office Hours meeting minutes to the Catena-X blog.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/337
> docs: add office hour 03112023

- blog/2023-11-17-OfficeHours.md
- add office hour 17-11-2023
fixes https://github.com/eclipse-tractusx/sig-infra/issues/374
- checkout branch
- npm install (optional)
- npm start
- verify changes
> chore: add meetings minutes for office hour on 17-11-2023

- blog/2024-01-19-NewHome.md
Do you think this is enough? Or shall we add a longer explanation?
> chore: add link to new office news location

- docs/internal/how-to-use-vault.md
- package-lock.json
- package.json
- update dependencies
- update Markdown link
- https://github.com/eclipse-tractusx/sig-infra/issues/348
- checkout branch
- npm install
- npm start
`npm run build` and `npm run serve` workd properly
> Info there will me more PR's against our page to reduce the information for our page
> chore: update docusaurus to current version

- package-lock.json
- package.json
- update docusaurus version
- new release for docusaurus
- checkout this branch
- npm install (optional)
- npm start
- verify changes
> chore: update docusaurus to version 3.2.1
